/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevServerPreviewRouteImport } from './routes/dev-server-preview'
import { Route as DevLogsPopoutRouteImport } from './routes/dev-logs-popout'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChicoRouteImport } from './routes/_chico'
import { Route as ChicoIndexRouteImport } from './routes/_chico.index'

const DevServerPreviewRoute = DevServerPreviewRouteImport.update({
  id: '/dev-server-preview',
  path: '/dev-server-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLogsPopoutRoute = DevLogsPopoutRouteImport.update({
  id: '/dev-logs-popout',
  path: '/dev-logs-popout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChicoRoute = ChicoRouteImport.update({
  id: '/_chico',
  path: '/chico',
  getParentRoute: () => rootRouteImport,
} as any)
const ChicoIndexRoute = ChicoIndexRouteImport.update({
  id: '/chico/',
  path: '/',
  getParentRoute: () => ChicoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/dev-logs-popout': typeof DevLogsPopoutRoute
  '/dev-server-preview': typeof DevServerPreviewRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings': typeof ChatSettingsRoute
  '/chico': typeof ChicoRouteWithChildren
  '/chico/': typeof ChicoIndexRoute
}
export interface FileRoutesByTo {
  '/dev-logs-popout': typeof DevLogsPopoutRoute
  '/dev-server-preview': typeof DevServerPreviewRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/chico': typeof ChicoRouteWithChildren
  '/chico/': typeof ChicoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/dev-logs-popout': typeof DevLogsPopoutRoute
  '/dev-server-preview': typeof DevServerPreviewRoute
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chico': typeof ChicoRouteWithChildren
  '/_chico/': typeof ChicoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-logs-popout'
    | '/dev-server-preview'
    | '/$threadId'
    | '/settings'
    | '/chico'
    | '/chico/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dev-logs-popout'
    | '/dev-server-preview'
    | '/$threadId'
    | '/settings'
    | '/'
    | '/chico'
    | '/chico/'
  id:
    | '__root__'
    | '/_chat'
    | '/dev-logs-popout'
    | '/dev-server-preview'
    | '/_chat/$threadId'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chico'
    | '/_chico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  DevLogsPopoutRoute: typeof DevLogsPopoutRoute
  DevServerPreviewRoute: typeof DevServerPreviewRoute
  ChicoRoute: typeof ChicoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev-server-preview': {
      id: '/dev-server-preview'
      path: '/dev-server-preview'
      fullPath: '/dev-server-preview'
      preLoaderRoute: typeof DevServerPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-logs-popout': {
      id: '/dev-logs-popout'
      path: '/dev-logs-popout'
      fullPath: '/dev-logs-popout'
      preLoaderRoute: typeof DevLogsPopoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chico': {
      id: '/_chico'
      path: '/chico'
      fullPath: '/chico'
      preLoaderRoute: typeof ChicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chico/': {
      id: '/_chico/'
      path: '/'
      fullPath: '/chico/'
      preLoaderRoute: typeof ChicoIndexRouteImport
      parentRoute: typeof ChicoRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ChicoRouteChildren {
  ChicoIndexRoute: typeof ChicoIndexRoute
}

const ChicoRouteChildren: ChicoRouteChildren = {
  ChicoIndexRoute: ChicoIndexRoute,
}

const ChicoRouteWithChildren = ChicoRoute._addFileChildren(ChicoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  DevLogsPopoutRoute: DevLogsPopoutRoute,
  DevServerPreviewRoute: DevServerPreviewRoute,
  ChicoRoute: ChicoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
